### ISSUE TITLE
Setup automatic deployments with github

### ISSUE THREAD

**Issue by JessePeplinski** [kitchen-assistant/progressive-web-app#7]
https://www.youtube.com/watch?v=QLVzozWDYAs

**Comment by PK4ever** [comment]
DEPLOYING WITH GITHUB

Create a .travis.yml file and add it to the git repository/project
run the command "firebase login:ci" to get a firebase tocken
login to travise and assign the tocken as "FIREBASE_TOKEN" in settings
push the project to github to deploy
